# Generated by Django 4.2.23 on 2025-07-17 10:09

from django.db import migrations
import givora_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('givora_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', givora_app.models.UserManager()),
            ],
        ),
    ]
