# Generated by Django 4.2.23 on 2025-09-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givora_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('money', 'Money'), ('items', 'Items'), ('food', 'Food'), ('grocery', 'Grocery'), ('medicine', 'Medicine')], max_length=20),
        ),
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(max_length=100)),
                ('target_group', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='givora_app.donation')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_type', models.CharField(max_length=100)),
                ('target_group', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_details', to='givora_app.donation')),
            ],
        ),
    ]
